channels:
  - conda-forge
dependencies:
  - python=3.7
  - bokeh=1.4.0
  - dask=2.9.1
  - dask-image=0.2.0
  - dask-ml=1.2.0
  - dask-labextension=1.1.0
  - jupyterlab=1.*
  - nodejs=10.15
  - notebook<5.7.5
  - tornado=5
  - numpy=1.17
  - python-graphviz
  - seaborn
  - matplotlib
  - nbserverproxy
  - pyscal
  - lammps
  - pylammpsmpi
